### ISSUE TITLE
Brushes don't work 

### ISSUE THREAD

**Issue by Kookodem** [Ellivers/WorldTool#1]
When I try to use select brush, this appears :
`Unknown function`
`worldtool:ui/tool_brush/select_brush/structure`
Instead of structure you can put any kind of brush. 
Using 21w05b

**Comment by Ellivers** [comment]
WorldTool doesn't currently work in snapshots as-is. Have you followed the steps I've listed to make it work in 1.17?

**Comment by Ellivers** [comment]
If you have any further questions, feel free to ask on my discord. The link's in the readme.
I'll close this now, as I'd prefer keeping issues as bugs and perhaps feature requests.
