### ISSUE TITLE
Using worldtool in custom dimensions

### ISSUE THREAD

**Issue by AzureLignus** [Ellivers/WorldTool#2]
I'm using your worldtool for a build project and I've come across the very specific bug that it cannot be used in custom dimensions. I'm not sure how fixable this problem really even is given how specific it is.

In my screenshots below you can see my selection area, selecting a block, hitting enter, and then it resulting in placing zero blocks. Even though doing so outside of my custom dimension in the same singlerplayer would results in it working fine 

![2021-08-21_18 45 33](https://user-images.githubusercontent.com/89321920/130336621-cd0498de-4b57-4ca3-9f11-30061d18ccd6.png)
![2021-08-21_18 45 40](https://user-images.githubusercontent.com/89321920/130336623-adfeccfd-ef8c-4e4f-b7a2-92b2cea06f32.png)
![2021-08-21_18 45 45](https://user-images.githubusercontent.com/89321920/130336624-b5650d3e-b8ae-40a2-ba3a-51815139bc0d.png)

Like I said I'm not sure how you would go about fixing this as it doesn't seem like your functions do any dimension-specific calls, but I wanted to bring it to your attention nonetheless because I found it interesting.

Thanks for your hard work! This tool is amazing

**Comment by Ellivers** [comment]
The docs state
"When using WorldTool in a custom dimension, make sure the chunk at 0 0 is loaded and there is a block at 0 0 13, by running `/forceload add 0 0` and `/function worldtool:init/set_base_blocks` in that dimension."
Try that and see if it solves the issue.

**Comment by AzureLignus** [comment]
> 
> 
> The docs state
> "When using WorldTool in a custom dimension, make sure the chunk at 0 0 is loaded and there is a block at 0 0 13, by running `/forceload add 0 0` and `/function worldtool:init/set_base_blocks` in that dimension."
> Try that and see if it solves the issue.

Wow i don't know how I managed to not read that note at the top of the documentation. That absolutely worked! Thanks so much for your quick reply!
