### ISSUE TITLE
Icon is literally VMware Workstation's logo

### ISSUE THREAD

**Issue by y2k04** [Ellivers/WorldTool#4]
VMware Workstation logo for reference
![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Vmware_workstation_16_icon.svg/200px-Vmware_workstation_16_icon.svg.png)

**Comment by Ellivers** [comment]
With how simple the icon is, it was bound to look like an already existing logo. For now, I think they look different enough, but I'm definitely going to make it something more unique and recognizable in the future.
