### ISSUE TITLE
Can I add a german translation?

### ISSUE THREAD

**Issue by Atten007** [Ellivers/WorldTool#9]
Hello! I'm from Germany and I have installed this data pack on my world. I have to say, that it's really nice. Now I want to upload my world (with the data pack installed) to my server. My server is a german server, so my question is: Can I publicly translate this data pack to German (Germany), that my friends (and other german Minecraft players) can better understand it? Greetings, Atten007 😊

**Comment by Ellivers** [comment]
I have now added German to [Crowdin](https://crowdin.com/project/worldtool), so feel free to translate it there!
